### PR TITLE
various launch docs

### PR DESCRIPTION
**Pull request by lsankar4033**
top-level README, nymjs README, basic contribution guidelines

TODO:
- [x] add note on independent verifiability of API + public API docs
- [x] add note on security properties of the scheme

### CODE REVIEW

**Comment by lsankar4033** [comment]
@amirgamil any information that's critically missing from this top-level doc?

**Comment by cha0sg0d** [comment]
@lsankar4033 Do we want the nouns svg image on the readme as a top-level image?

**Comment by cha0sg0d** [comment]
@lsankar4033 Farcaster protocol has everything left-centered: https://github.com/farcasterxyz/protocol. Perhaps we want to do the same?

**Comment by lsankar4033** [comment]
@amirgamil + @DanTehrani anything you'd add to the README after last commit here?

**Comment by amirgamil** [comment]
lgtm

**Comment by lsankar4033** [comment]
> @lsankar4033 Farcaster protocol has everything left-centered: https://github.com/farcasterxyz/protocol. Perhaps we want to do the same?

ah i don't mind either way; was copying snapshot labs - https://github.com/snapshot-labs/snapshot

both seem nice for different reasons! I like the feel of top-level readme with a centered heading

**Pull request merged**
