### PR TITLE
Mobile FAQ / Transitions

### PR DESCRIPTION
**Pull request by grace-fagan**
- [x] Mobile support for FAQ toggle (modal vs popover)
<div style="display: flex">
Screenshot 2023-06-19 at 10 55 14 AM
Screenshot 2023-06-19 at 10 55 20 AM
</div>

- [x] Add transition to modal and popover
- [x] Add transition to menus (notifications / filters)
- [x] Fix next.js image warnings

Testing #195

### CODE REVIEW

**Comment by cha0sg0d** [comment]
@grace-fagan I like the question mark on desktop as well.

**Comment by cha0sg0d** [comment]
#194

**Comment by cha0sg0d** [comment]
#191

**Comment by lsankar4033** [comment]
nice!

**Pull request merged**
